gobeyondidentity/developer-docs

- package.json
- patch.sh
- yarn.lock
A couple of vulnerabilities were found in 0.4.0 of docusaurus-preset-openapi. This updates that package to 0.5.0.
> Update docusaurus preset openapi

- package.json
- yarn.lock
The openapi generator we're using released an update that is compatible with the latest docusuarus.
> Update to latest docusaurus

- api/v1/openapi.yaml
- docusaurus.config.js
- package.json
- yarn.lock
- Switches us over to using redoc for openapi doc display
- Updates our openapi yaml to the latest version (last version wasn't compiling with redoc for some reason)
> Switch v1 docs over to redocusaurus

- docs/javascript-sdk/overview.md
- docs/kotlin-sdk/documentation.md
- docs/kotlin-sdk/getting-started.md
- docs/kotlin-sdk/overview.md
This PR will adds high level overview documentation for the Kotlin SDK. This is not meant to be an in depth integration guide. 
See SDK preview [here](https://developer-docs-git-sdk-overview-kotlin-beyondidentity.vercel.app/docs/v1/kotlin-sdk/overview).
> Overview docs for Kotlin SDK

- static/api/v1/openapi.yaml
Update `static/api/v1/openapi.yaml` to use the latest draft of the Management API openapi.yaml.
> Update v1 OpenAPI specification (July 12)

- static/api/v1/openapi.yaml
Update `static/api/v1/openapi.yaml` to use the v1.0.0 release of the v1 API OpenAPI specification.
> Publish v1.0.0 of the v1 API OpenAPI specification

- docs/platform-overview/passkeys-and-devices/passkey-creation.md
- static/api/v1/openapi.yaml
Publish v1.0.1 of the v1 API OpenAPI specification and fix the requests in the passkey creation guide.
> Publish v1.0.1 of the v1 API OpenAPI specification

- static/api/v1/openapi.yaml
Publish v1.0.2 of the v1 API OpenAPI specification.
> Publish v1.0.2 of the v1 API OpenAPI specification

- static/api/v1/openapi.yaml
Publish v1.1.0 of the v1 API OpenAPI specification.
> Publish v1.1.0 of the v1 API OpenAPI specification

- guides/sso-integrations/integrate-with-curity.md
> Update Curity integration guide for v1

- guides/sso-integrations/integrate-with-auth0.md
- guides/sso-integrations/integrate-with-curity.md
- guides/sso-integrations/integrate-with-keycloak.md
> Update KeyCloak integration guide for v1

- guides/bubble-io-integration.md
user needs to tick '3rd party developer' box.
> Add a new direction for the bubble.io plugin search. 

- docs/getting-started.md
> Remove extra ` from demo link

- guides/bubble-io-integration.md
- guides/index.md
- guides/integrate-wordpress.md
Wordpress integration is working. Linking to the guide.
Also added a useful instruction to the bubble.io guide about what happens with the Log IN action.
> Link to wordpress integration guide

- docs/sdks/flutter-sdk/overview.md
- docs/sdks/javascript-sdk/overview.md
- docs/sdks/kotlin-sdk/overview.md
- docs/sdks/react-native-sdk/overview.md
- docs/sdks/swift-sdk/overview.md
This should be updated on:
- Developer Docs
- Github Readme
> [Flutter] Update documentation to include import instructions

- guides/bubble-io-integration.md
- guides/index.md
- guides/integrate-wordpress.md
- guides/sso-integrations/integrate-with-auth0.md
- guides/sso-integrations/integrate-with-azureb2c.md
- guides/sso-integrations/integrate-with-bi-workforce.md
- guides/sso-integrations/integrate-with-cognito.md
- guides/sso-integrations/integrate-with-curity.md
- guides/sso-integrations/integrate-with-keycloak.md
- guides/sso-integrations/integrate-with-okta.md
- sidebars.js
- sidebarsGuides.js
- versioned_docs/version-v0/sso-integrations/integrate-with-auth0.md
Some integrations were missing on the sidebar and updated titles
> Fix Guide Sidebar and Titles

- src/components/CredentialModal.jsx
- src/pages/try-it-out/index.jsx
- src/utils/bi-sdk-js.js
- Validation for usernames with spaces
- Capitalization of passkey in different contexts
- Padding between delete and close buttons
- Only blur on first run through
> Secure Customer Channel Feedback

- docs/workflows/api-token.md
- docs/workflows/user-provisioning.md
Address some feedback after merging and opening up the review to more people. 
To view the rendered version click on `Visit Preview`
> More User Provisioning

- docusaurus.config.js
Adds additionalLanguages: ['dart','kotlin','swift'] (javascript is already supported)
> Added additional syntax highlighting support for SDKs

- docs/workflows/api-token.md
As per Colton's request, I'm adding some documentation for listing tokens for an application or identity. Let me know if I need to elaborate somewhere or reword things.
> add docs for listing tokens

- docs/platform-overview/authenticator-config.md
added mermaid sequence diagrams for bind flows and re-organized doc to match the order the configs appear in the console, remove duplication, and overall edit.
> update authenticator config doc

- docs/workflows/api-token.md
- docs/workflows/applications.md
- docs/workflows/authentication.md
- docs/workflows/bind-passkey.md
- docs/workflows/realms.md
- docs/workflows/sdk-setup.mdx
- docs/workflows/user-provisioning.md
Click on `Visit Preview` to view the generated version: https://developer-docs-git-devx-1172-applications-beyondidentity.vercel.app/docs/v1/workflows/applications
> Create an Application

- docs/sdks/javascript-sdk/Reference/js-sdk-passkey-type.md
- docs/workflows/account-setup.md
- docs/workflows/api-token.md
- docs/workflows/applications.md
- docs/workflows/authentication.md
- docs/workflows/authenticator-types.md
- docs/workflows/bind-passkey.md
- docs/workflows/realms.md
- docs/workflows/sdk-setup.mdx
- docs/workflows/user-provisioning.md
- Update numbering in workflows section
- Fix passkey type in JS SDK reference
> A few small fixes

- static/api/v1/openapi.yaml
Publish v1.2.0 of the v1 API OpenAPI specification.
> Publish v1.2.0 of the v1 API OpenAPI specification

- docs/workflows/api-token.md
This PR adds example responses for introspect endpoint. It also fixes curl requests that use form request body. 
We need to check what code is generated from the curl commands.
> AUTH-1465 add examples for introspect endpoint

- docs/workflows/api-token.md
Some things came up during API review in zero repo, which caused me to change the URLs and response shape.
This change reflects my latest changes in zero.
> update list tokens example response

- docs/workflows/api-token.md
This adds some basic documentation for the `custom_claims` and `expiration_time` features within secure customer.
> Auth 1577: Update developer documentation with new token endpoint features

- docs/workflows/api-token.md
This PR adds a short section on how to use refresh tokens.
> Add section about refreshing tokens

- static/api/v1/openapi.yaml
Publish v1.3.0 of the v1 API OpenAPI specification.
> Publish v1.3.0 of the v1 API OpenAPI specification

- docs/authentication/authentication.mdx
- docs/includes/_authentication-profile-table1.mdx
- docs/includes/_authentication-profile-table2.mdx
- docs/includes/_authentication-profile-table3.mdx
- Adds **Authentication Profile** to **Hosted Web** **Authenticator Config**
> Hosted Login: Authentication Profile

- docs/authentication/authentication.mdx
There is currently an issue with creating a hosted web authenticator application. These are some workaround steps.
> Hosted Login: Workaround

- docs/authentication/authentication.mdx
We just released a fix for this so we should be able to revert this now
> Revert "Hosted Login: Workaround"

- docs/sdks/js-reference-guide/js-sdk-authenticate.md
- docs/sdks/js-reference-guide/js-sdk-authenticateOtp.md
- docs/sdks/js-reference-guide/js-sdk-getAuthenticationContext.md
```bash
yarn build
```
Adds `json` to json code blocks
> Add `json` to json code blocks

- src/css/custom.css
Already merged here: https://github.com/gobeyondidentity/developer-docs/pull/313/files
merging this to main branch
> Fix nav titles to have cursor pointer

- docs/authentication/embedded-sdk-add-idp-federated.mdx
- docs/authentication/embedded-sdk-add-otp-email.mdx
- docs/authentication/embedded-sdk-add-passkeys-existing.mdx
- docs/authentication/hosted-add-fido2.mdx
- docs/authentication/hosted-add-idp-federated.mdx
- docs/authentication/hosted-add-otp-email.mdx
- docs/authentication/hosted-add-passkeys-existing.mdx
- docs/how-to/add-an-identity.md
- docs/how-to/add-passkey.md
- docs/includes/_bind-passkey-frontend-email.mdx
- docs/includes/_bind-passkey-frontend-return.mdx
- docs/includes/_bind-passkey-to-an-identity.mdx
- docs/includes/_passkey-binding-methods.mdx
- sidebars.js
Add information about passkey creation for both HWA and Embedded SDK
Direct link: https://developer-docs-git-add-a-passkey-update-beyondidentity.vercel.app/docs/next/add-passkey
> Update "add a passkey document" with more detail and addressing highlighted text

- docs/get-started/get-started.mdx
- docs/introduction.mdx
- src/css/custom.css
- static/img/Angular_full_color_logo.svg
- static/img/React-icon.svg
```bash
yarn build
```
- Add hover effects to all cards
- Switch "Foundations" and "Getting Started" on the main page
- Add small icons next to "Foundations" and "Getting Started" so they stand out a bit
> Small UI Fixes

- docs/api-tokens/api-token-overview.md
- docs/authentication/authentication.mdx
- docs/authentication/embedded-sdk-add-passkeys.mdx
- docs/authentication/hosted-add-authentication.mdx
- docs/foundations/universal-passkeys.mdx
- docs/glossary.mdx
- docs/how-to/add-an-application.mdx
- docs/how-to/create-realm.mdx
- docs/includes/_app_external_protocol_properties.mdx
- docs/includes/_configure_oidc_client_library.mdx
- docs/includes/_passkeys-and-devices-overview.mdx
- docs/includes/_sdks/_flutter-auth0.mdx
- docs/includes/_sdks/_javascript-auth0.mdx
- docs/integration-guides/auth0.md
- docs/integration-guides/azure-ad-b2c.md
- docs/integration-guides/expo-react-native.md
- docs/integration-guides/firebase.md
- docs/integration-guides/integration-guides.mdx
- docs/integration-guides/keycloak.md
- docs/integration-guides/okta.mdx
- sidebars.js
```bash
yarn build
```
1) Resolve yellow-highlighted inline comments in various documents
2) Update sidebars to add "Create Beyond Identity Management API Token" doc and remove placeholder for workforce integration guide
> address inline comments in various docs

- static/api/v1/openapi.yaml
```bash
yarn build
```
Publish v1.6.1 of the v1 API OpenAPI specification. This reverts all changes from v1.6.0 which were never published and updates the documentation for `DeleteRealm`.
> Publish v1.6.1 of the v1 API OpenAPI specification

- docs/resources.md
Added slack to support channel
```bash
yarn build
```
Describe your pull request.
> Add slack to support channel link

- docs/authentication/embedded-sdk-add-authentication.mdx
- docs/authentication/embedded-sdk-add-otp-email.mdx
- docs/get-started/getting-started-nextjs.mdx
```bash
yarn build
```
- [Fix numbering in nextjs getting started guide](https://github.com/gobeyondidentity/developer-docs/commit/5fe821bed04f8d23041b4b0d7f8d43fab502db6f)
- [Fix MultiLanguageCodeBlocks in docs/authentication](https://github.com/gobeyondidentity/developer-docs/commit/c6c5617a6b5c78fb43f43486e469befb14f78478)
> Minor Fixes

- docs/foundations/universal-passkeys.mdx
```bash
yarn build
```
Describe your pull request.
> Correct link for TPM

- static/api/v1/openapi.yaml
Adding SCIM V1 to the docs + other updates since this change
> Add SCIM to openapi

- package.json
- yarn.lock
```bash
yarn build
```
Describe your pull request.
> Update bi-sdk-js to 3.0.6

- docs/get-started/get-started.mdx
- docs/get-started/getting-started-angular.mdx
- docs/get-started/getting-started-nextjs.mdx
- docs/get-started/getting-started-react.mdx
- docs/includes/_developer-sign-up-process.mdx
- package.json
- Updated language around demo accounts for Getting Started sections
```bash
yarn build
```
Describe your pull request.
> Updated getting started pages to remove references to free demo account

- docusaurus.config.js
- src/components/HomepageFeatures.js
- src/components/HomepageFeatures.module.css
- src/pages/index.js
```bash
yarn build
```
Fixed links on the homepage. Other minor changes.
> Homepage updates - fix links
